plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'com.google.gms.google-services'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
}


android {
    namespace 'com.resieasy.rezirent'
    compileSdk 34

    buildFeatures{
        viewBinding=true
    }

    defaultConfig {
        applicationId "com.resieasy.rezirent"
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName "1.0.5"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.google.firebase:firebase-auth:23.2.0'
    implementation 'com.google.firebase:firebase-database:21.0.0'
    implementation 'com.google.firebase:firebase-storage:21.0.1'
    implementation 'com.google.firebase:firebase-analytics:22.4.0'
    implementation 'com.google.firebase:firebase-firestore:25.1.4'
    implementation 'com.google.firebase:firebase-messaging:24.1.1'
    implementation 'com.google.firebase:firebase-inappmessaging-display:21.0.2'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    //RxJava
    implementation 'io.reactivex.rxjava3:rxjava:3.1.10'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'

    //hilt
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-compiler:2.51.1"

    //Imgae picker
    //implementation 'com.github.dhaval2404:imagepicker:2.1'
    //Picasso
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.google.android.gms:play-services-auth:21.3.0'

    //image slider
    implementation 'com.github.denzcoskun:ImageSlideshow:0.1.2'

    //refreshrecyclerview

    implementation 'androidx.recyclerview:recyclerview:1.3.2'

    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    //googlemapshow
    implementation 'com.google.android.gms:play-services-maps:19.0.0'

    //getcurrentlocation
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    
    //messaging
    implementation 'com.android.volley:volley:1.2.1'
    implementation("com.squareup.okhttp3:okhttp:4.12.0")


    //admob
    implementation 'com.google.android.gms:play-services-ads:23.6.0'

    //in app update
    implementation("com.google.android.play:app-update:2.1.0")

    //facebook shimmer
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

    //onesignal
    implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'


     //viewmodel
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.0'

    // Required for viewModels() in Activity
     implementation 'androidx.activity:activity-ktx:1.8.2'

    // Required for viewModels() in Fragment
    implementation 'androidx.fragment:fragment-ktx:1.6.2'

    //Room
    implementation "androidx.room:room-runtime:2.7.1"
    kapt "androidx.room:room-compiler:2.7.1"
    implementation "androidx.room:room-ktx:2.7.1"


    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3") // Important for Android


}

// Allow references to generated code
kapt {
    correctErrorTypes true
}
