package com.resieasy.rezirent.Class

data class FacilityClass(
    val clean: String = "",
    val ac: String = "",
    val rowater: String = "",
    val water: String = "",
    val wifi: String = "",
    val cctv: String = "",
    val bed: String = "",
    val hotwater: String = "",
    val table: String = "",
    val locker: String = "",
    val fan: String = "",
    val powerbackup: String = "",
    val washing: String = "",
    val security: String = "",
    val inout: String = "",
    val attach: String = "",
    val shower: String = "",
    val parking: String = "",
    val mess: String = "",
    val tv: String = "",
    val gas: String = "",
    val dining: String = "",
    val refrigerator: String = "",
    val sofa: String = "",
    val elevator: String = "",
    val play: String = "",
    val gym: String = "",
    val studyroom: String = "",
    val kitchen: String = "",
    val balcony: String = "",
    val indian: String = "",
    val western: String = "",
    val terrace: String = "",
    val furnished: String = "",
    val more: String = ""
)
